### PR TITLE
makectanzip: generate TDS-compliant archive

### PR DESCRIPTION
**Pull request by jspitz**
Also don't include some files which are not meant to be distributed.

### CODE REVIEW

**Comment by jspitz** [comment]
Wait a minute. I just saw that the *.tex files in tex are in fact used. I'll update the PR in a minute.

**Comment by jspitz** [comment]
Updated.

**Comment by reutenauer** [comment]
Thanks, but I don’t think that’s going to fly with CTAN.  They [explicitly discourage](https://ctan.org/help/upload-pkg) from using TDS (“it should be omit­ted for in­stance for nor­mal LaTeX pack­ages”), and if we want to use that structure, we need to add a `luabidi.tds.zip` _next_ to the so-called flat structure that CTAN prefers (see [their instructions](https://ctan.org/TDS-guidelines)).  I believe [this commit](https://github.com/bidi-tex/luabidi/commit/ceef496) I’ve just made does the trick.

**Comment by jspitz** [comment]
OK, fine.

**Pull request closed without merging**
